name: Publish

on:
  release:
    types: [ released ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v3

      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.OS }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4

      - name: 🔍 Install dependencies
        run: pnpm install

      - name: 🛠 Build
        run: pnpm run build

      - name: 🚀 Publish
        run: pnpm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

